version: "1"

services:

  celery:
    build: .
    command: >
      bash -c  "celery -A autoCelery.task worker -B -l INFO &
      uvicorn MovieCrawler.asgi:application --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis_celery
      - database

  redis_celery:
    image: redis
    ports:
      - "6379:6379"

  database:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ram1999